name: pos_by_sakir
description: Pos Management app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  riverpod:
  flutter_riverpod:
  grock:
  flutter_slidable:
  cached_network_image:
  bordered_text:
  vertical_tabs_flutter:
  http:
  flutter_hooks:
  rflutter_alert:
  modal_bottom_sheet: ^3.0.0-pre
  badges: ^3.1.2
  cool_alert: ^2.0.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  google_fonts: 6.1.0
  progress_dialog_null_safe: ^1.0.7
  select_form_field: ^2.2.0
  flutter_form_builder: ^9.1.1
  form_builder_validators:
  flutter_svg: ^2.0.9
  carousel_slider: ^4.1.1
  open_street_map_search_and_pick: ^0.1.1
  image_picker: ^1.0.7
  multi_select_flutter: ^4.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
    - family: Robot
      fonts:
        - asset: assets/fonts/RobotoMono-Medium.ttf
